### ISSUE TITLE
publish = false is not respected

### ISSUE THREAD

**Issue by adukstad** [equinor/farfetched-actions#15]
Tried to deploy an app with publish set to false, but it still got published / not in preview

**Comment by adukstad** [comment]
example push which shows publish set to `false `and still publishing: https://github.com/equinor/spine-raphael/runs/6829429916?check_suite_focus=true

![image](https://user-images.githubusercontent.com/33690670/173051342-56c05d8b-ae86-492b-a010-3af1ea6225a3.png)
![image](https://user-images.githubusercontent.com/33690670/173051426-87c4cc87-9fe2-4c9c-ba2b-942b7d44416d.png)

**Comment by aigelonic** [comment]
Hopefully #16 fixed this.
Let me know @adukstad if it works for you now.
